[package]
name = "sqlite-tonbo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["tokio"]
tokio = ["dep:tokio", "tonbo/tokio"]
wasm = [
    "dep:wasm_thread",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "tonbo/wasm",
]

[dependencies]
flume = "0.11"
fusio = { path = "../fusio/fusio", package = "fusio", features = [
    "dyn",
    "fs",
    "aws",
] }
fusio-dispatch = { path = "../fusio/fusio-dispatch", package = "fusio-dispatch", features = ["aws"] }
futures-util = "0.3"
tokio = { version = "1.41", optional = true, features = ["rt-multi-thread"] }
tonbo = { path = "../yet-another-elsm", package = "tonbo", default-features = false, features = [
    "bytes",
], optional = true }
tonbo_net_client = { path = "../yet-another-elsm/tonbo_net_client", package = "tonbo_net_client" }

tonbo_macros = { git = "https://github.com/tonbo-io/tonbo", rev = "4844cb8409a48b680467705bb05cbcac2edcb8c6", package = "tonbo_macros" }
rusqlite = { git = "https://github.com/tonbo-io/rusqlite", branch = "wasm32-unknown-unknown", features = [
    "vtab",
    "bundled",
] }
sqlparser = "0.52"

wasm-bindgen = { version = "0.2.93", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
wasm_thread = { version = "0.3", optional = true }

log = "0.4"
console_log = { version = "1.0", features = ["color"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[patch.crates-io.wasm_thread]
git = "https://github.com/Twey/wasm_thread"
branch = "post-message"

[workspace]
members = [
    "tests/sqllogictest",
]
